### ISSUE TITLE
Request for the pretrained models

### ISSUE THREAD

**Issue by sunhee-hwang** [kdhht2334/AVCE_FER#1]
Can you share the pretrained models?

**Comment by kdhht2334** [comment]
We upload pre-trained model weights.
Because of private issue about lab research, we only upload weights trained on AFEW-VA.

If you want a demo implementation, the weights for the demo are also included in the `AVCE_demo` folder.

**Comment by sunhee-hwang** [comment]
Can you upload weight for the encoder? 
There's no 'Sparse_cont_enc.t7' in AVCE_demo/weights

**Comment by kdhht2334** [comment]
First of all, sorry for the inconvenience.

I upload 'Sparse_cont_enc.t7' in AVCE_demo/weights.

Also, you can enjoy enhanced version of FER demo at `https://github.com/kdhht2334/ELIM_FER/tree/main/demo`.


Thanks.
