### ISSUE TITLE
missing keys when loading regressor

### ISSUE THREAD

**Issue by mdabbah** [kdhht2334/AVCE_FER#3]
Hi,
First of all, Thank you so much for your work and sharing your code and pretrained weights!
I would appreciate if you could help me with a peroblem regarding loading the network

so i'm looking at the code an experimenting with it (more specifically the demo code)
there I see that the network is loaded in lines (320-322 demo-> run.py)

```
        encoder, regressor = nn_output()
        encoder.load_state_dict(torch.load('/home/daehakim/Desktop/FER_int_system/AVCE_demo/weights/Sparse_cont_enc.t7'), strict=False)
        regressor.load_state_dict(torch.load('/home/daehakim/Desktop/FER_int_system/AVCE_demo/weights/Sparse_cont_reg.t7'), strict=False)
```
but when loading the weights i get missing keys warning in the reggressor line

```
_IncompatibleKeys(missing_keys=['lin2.weight', 'lin2.bias', 'pw_conv.weight', 'pw_conv.bias'], unexpected_keys=[])
```

could it be that the weights file `Sparse_cont_reg.t7` is corrupted / not up to date? could you please update it?

Thanks

**Comment by kdhht2334** [comment]
Hi,

In my case, I cannot see any error when running `run.py`.

Please check whether you loaded a function `Regressor_light_new` or not in `nn_output()` of `/my_util/fer_util.py`.

Specifically, you can check model details in `/my_util/fer_util.py`.

If this still doesn't solve the problem, please provide a detailed error log.
