### ISSUE TITLE
the dataset on which the model "Sparse_..._.t7" in AVCE_demo is trained?

### ISSUE THREAD

**Issue by Angus-GPZ** [kdhht2334/AVCE_FER#4]
May I inquire about the dataset on which the model "Sparse_..._.t7" in AVCE_demo is trained? I have noticed a significant disparity between the predicted outcomes and the labels when evaluating it on datasets like AFEW-VA. Could you kindly provide some insights into this matter?

**Comment by kdhht2334** [comment]
Hi,

Weights in demo folder are trained using both AFEW-VA and Aff-wild.

That's why significant disparity may happen.

Please also note that you have to do preprocessing procedure (e.g. face crop and remove fade in/out scene).

  - Both Aff-wild(/2) and AFEW-VA datasets.

**Comment by Angus-GPZ** [comment]
Could you please provide your preprocessing code? It seems that there isn't any method mentioned in https://pytorch.org/tutorials/beginner/data_loading_tutorial.html for face crop or removing fade in/out scenes. Thank you very much for your assistance and time.

**Comment by kdhht2334** [comment]
Here you are.

In my case, all data are preprocessed by MTCNN.

Please see https://github.com/kdhht2334/AVCE_FER/blob/main/preprocessing.py

**Comment by Angus-GPZ** [comment]
Thanks a lot
